const userapi = [
  {
    id: 1,
    name: "User One",
    description: "Description for user one",
    avatar: "https://api.dicebear.com/7.x/miniavs/svg?seed=1",
  },
  {
    id: 2,
    name: "User Two",
    description: "Description for user two",
    avatar: "https://api.dicebear.com/7.x/miniavs/svg?seed=2",
  },
  {
    id: 3,
    name: "User Three",
    description: "Description for user three",
    avatar: "https://api.dicebear.com/7.x/miniavs/svg?seed=3",
  },
  {
    id: 4,
    name: "User Four",
    description: "Description for user four",
    avatar: "https://api.dicebear.com/7.x/miniavs/svg?seed=4",
  },
  {
    id: 5,
    name: "User Five",
    description: "Description for user five",
    avatar: "https://api.dicebear.com/7.x/miniavs/svg?seed=5",
  },
  {
    id: 6,
    name: "User Six",
    description: "Description for user six",
    avatar: "https://api.dicebear.com/7.x/miniavs/svg?seed=6",
  },
  {
    id: 7,
    name: "User Seven",
    description: "Description for user seven",
    avatar: "https://api.dicebear.com/7.x/miniavs/svg?seed=7",
  },
  {
    id: 8,
    name: "User Eight",
    description: "Description for user eight",
    avatar: "https://api.dicebear.com/7.x/miniavs/svg?seed=8",
  },
  {
    id: 9,
    name: "User Nine",
    description: "Description for user nine",
    avatar: "https://api.dicebear.com/7.x/miniavs/svg?seed=9",
  },
  {
    id: 10,
    name: "User Ten",
    description: "Description for user ten",
    avatar: "https://api.dicebear.com/7.x/miniavs/svg?seed=10",
  },
  {
    id: 11,
    name: "User Eleven",
    description: "Description for user eleven",
    avatar: "https://api.dicebear.com/7.x/miniavs/svg?seed=11",
  },
  {
    id: 12,
    name: "User Twelve",
    description: "Description for user twelve",
    avatar: "https://api.dicebear.com/7.x/miniavs/svg?seed=12",
  },
  {
    id: 13,
    name: "User Thirteen",
    description: "Description for user thirteen",
    avatar: "https://api.dicebear.com/7.x/miniavs/svg?seed=13",
  },
  {
    id: 14,
    name: "User Fourteen",
    description: "Description for user fourteen",
    avatar: "https://api.dicebear.com/7.x/miniavs/svg?seed=14",
  },
  {
    id: 15,
    name: "User Fifteen",
    description: "Description for user fifteen",
    avatar: "https://api.dicebear.com/7.x/miniavs/svg?seed=15",
  },
  {
    id: 16,
    name: "User Sixteen",
    description: "Description for user sixteen",
    avatar: "https://api.dicebear.com/7.x/miniavs/svg?seed=16",
  },
  {
    id: 17,
    name: "User Seventeen",
    description: "Description for user seventeen",
    avatar: "https://api.dicebear.com/7.x/miniavs/svg?seed=17",
  },
  {
    id: 18,
    name: "User Eighteen",
    description: "Description for user eighteen",
    avatar: "https://api.dicebear.com/7.x/miniavs/svg?seed=18",
  },
  {
    id: 19,
    name: "User Nineteen",
    description: "Description for user nineteen",
    avatar: "https://api.dicebear.com/7.x/miniavs/svg?seed=19",
  },
  {
    id: 20,
    name: "User Twenty",
    description: "Description for user twenty",
    avatar: "https://api.dicebear.com/7.x/miniavs/svg?seed=20",
  },
  {
    id: 21,
    name: "User Twenty-One",
    description: "Description for user twenty-one",
    avatar: "https://api.dicebear.com/7.x/miniavs/svg?seed=21",
  },
  {
    id: 22,
    name: "User Twenty-Two",
    description: "Description for user twenty-two",
    avatar: "https://api.dicebear.com/7.x/miniavs/svg?seed=22",
  },
  {
    id: 23,
    name: "User Twenty-Three",
    description: "Description for user twenty-three",
    avatar: "https://api.dicebear.com/7.x/miniavs/svg?seed=23",
  },
  {
    id: 24,
    name: "User Twenty-Four",
    description: "Description for user twenty-four",
    avatar: "https://api.dicebear.com/7.x/miniavs/svg?seed=24",
  },
  {
    id: 25,
    name: "User Twenty-Five",
    description: "Description for user twenty-five",
    avatar: "https://api.dicebear.com/7.x/miniavs/svg?seed=25",
  },
  {
    id: 26,
    name: "User Twenty-Six",
    description: "Description for user twenty-six",
    avatar: "https://api.dicebear.com/7.x/miniavs/svg?seed=26",
  },
  {
    id: 27,
    name: "User Twenty-Seven",
    description: "Description for user twenty-seven",
    avatar: "https://api.dicebear.com/7.x/miniavs/svg?seed=27",
  },
  {
    id: 28,
    name: "User Twenty-Eight",
    description: "Description for user twenty-eight",
    avatar: "https://api.dicebear.com/7.x/miniavs/svg?seed=28",
  },
  {
    id: 29,
    name: "User Twenty-Nine",
    description: "Description for user twenty-nine",
    avatar: "https://api.dicebear.com/7.x/miniavs/svg?seed=29",
  },
  {
    id: 30,
    name: "User Thirty",
    description: "Description for user thirty",
    avatar: "https://api.dicebear.com/7.x/miniavs/svg?seed=30",
  },
  {
    id: 31,
    name: "User Thirty-One",
    description: "Description for user thirty-one",
    avatar: "https://api.dicebear.com/7.x/miniavs/svg?seed=31",
  },
  {
    id: 32,
    name: "User Thirty-Two",
    description: "Description for user thirty-two",
    avatar: "https://api.dicebear.com/7.x/miniavs/svg?seed=32",
  },
  {
    id: 33,
    name: "User Thirty-Three",
    description: "Description for user thirty-three",
    avatar: "https://api.dicebear.com/7.x/miniavs/svg?seed=33",
  },
  {
    id: 34,
    name: "User Thirty-Four",
    description: "Description for user thirty-four",
    avatar: "https://api.dicebear.com/7.x/miniavs/svg?seed=34",
  },
  {
    id: 35,
    name: "User Thirty-Five",
    description: "Description for user thirty-five",
    avatar: "https://api.dicebear.com/7.x/miniavs/svg?seed=35",
  },
  {
    id: 36,
    name: "User Thirty-Six",
    description: "Description for user thirty-six",
    avatar: "https://api.dicebear.com/7.x/miniavs/svg?seed=36",
  },
  {
    id: 37,
    name: "User Thirty-Seven",
    description: "Description for user thirty-seven",
    avatar: "https://api.dicebear.com/7.x/miniavs/svg?seed=37",
  },
  {
    id: 38,
    name: "User Thirty-Eight",
    description: "Description for user thirty-eight",
    avatar: "https://api.dicebear.com/7.x/miniavs/svg?seed=38",
  },
  {
    id: 39,
    name: "User Thirty-Nine",
    description: "Description for user thirty-nine",
    avatar: "https://api.dicebear.com/7.x/miniavs/svg?seed=39",
  },
  {
    id: 40,
    name: "User Forty",
    description: "Description for user forty",
    avatar: "https://api.dicebear.com/7.x/miniavs/svg?seed=40",
  },
];

export default userapi;
